python generate_instruct_qa_multiple_api.py \
        --category_type='6' \
        --query_list="/data/dataset/mapping/vid_valid_mapping.json" \
        --fewshot_path='/SeqMMLearning/instruct_generation/fewshot/single_turn' \
        --sys_msg_path="/SeqMMLearning/instruct_generation/system_msg.json" \
        --annot_path="/data/generate/ikea_preprocessed_data.json" \
        --manual_path="/data/dataset/manuals" \
        --save_path="/data/generate/qa_annot/single_turn/" \
        --mode='w_annot' \
        --api_mapping_path="/data/dataset/mapping/multiple_api_all_manual_genlist.json" \
        --api_num="6" \
